// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'game': string;
  'game__data-wrapper': string;
  'game__steps': string;
}
export const cssExports: CssExports;
export default cssExports;
