// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu': string;
  'menu__circle': string;
  'menu__circle-line': string;
  'menu__circle-link': string;
  'menu__circle-link-user': string;
  'menu__line': string;
  'menu__line-link': string;
  'menu__lines': string;
}
export const cssExports: CssExports;
export default cssExports;
