// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'rules': string;
  'rules__content': string;
  'rules__divider': string;
  'rules__title': string;
  'rules_text-indent': string;
}
export const cssExports: CssExports;
export default cssExports;
