ARG NODE_VERSION=16
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

RUN rm -rf /app/packages/server/dist/ && rm -rf /app/packages/client/dist/ && yarn build && yarn preview --scope server

EXPOSE $SERVER_PORT
CMD [ "node", "/app/packages/server/dist/index.js" ]