// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content-center': string;
  'red': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
