// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo': string;
  'logo__button': string;
  'logo__button_hidden': string;
  'logo__title': string;
}
export const cssExports: CssExports;
export default cssExports;
