// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'box__message': string;
  'box__resetBtn': string;
  'box__title': string;
  'errorFallback': string;
}
export const cssExports: CssExports;
export default cssExports;
