// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'date': string;
  'info': string;
  'info__commentsCount': string;
  'info__text': string;
  'topic': string;
  'topic__border': string;
  'topic__description': string;
  'topic__lastMessage': string;
  'topic__title': string;
  'username': string;
}
export const cssExports: CssExports;
export default cssExports;
