// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'triangles__item': string;
  'triangles__item_one': string;
  'triangles__item_three': string;
  'triangles__item_two': string;
}
export const cssExports: CssExports;
export default cssExports;
