// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MuiFormControl-root': string;
  'profile': string;
  'profile__form': string;
}
export const cssExports: CssExports;
export default cssExports;
