// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'box__message': string;
  'box__title': string;
  'comment': string;
  'comment__line': string;
  'date': string;
  'username': string;
}
export const cssExports: CssExports;
export default cssExports;
