// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MuiPagination-ul': string;
  'MuiTableBody-root': string;
  'MuiTableCell-root': string;
  'MuiTableHead-root': string;
  'leaders': string;
  'leaders__footer': string;
  'leaders__table': string;
  'leaders__title': string;
  'userCell': string;
}
export const cssExports: CssExports;
export default cssExports;
