// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'comments': string;
  'comments__header': string;
  'date': string;
  'forum': string;
  'forumSubPage': string;
  'forumSubPage__inputMsg': string;
  'forumSubPage__line': string;
  'forumSubPage__title_underline': string;
  'forumSubPage__topicDescription': string;
  'forum__content': string;
  'forum__header': string;
  'forum__text': string;
  'forum__title': string;
  'forum__topics': string;
  'info': string;
  'info__owner': string;
  'lastMsgText': string;
  'msgCount': string;
  'topicText': string;
  'username': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
