// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form__line': string;
  'form__title': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
