// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'notFoundPage': string;
  'notFoundPage__message': string;
  'notFoundPage__title': string;
}
export const cssExports: CssExports;
export default cssExports;
