// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MuiFormControl-root': string;
  'auth': string;
  'auth__form': string;
  'auth__title': string;
}
export const cssExports: CssExports;
export default cssExports;
